### ISSUE TITLE
Why does __init__.py not import anything?

### ISSUE THREAD

**Issue by nelsontodd** [cedricleroy/pyungo#22]
Hi. I understand this is a style choice, but why use an empty `__init__.py` instead of filling it with `from .core import *`? 
If you do it the second way, you can import with `from pyungo import Graph` instead of `from pyungo.core import Graph`, which is nice because I had no idea `core.py` existed inside of this package until I looked. Thank you!

**Comment by cedricleroy** [comment]
Thanks for the suggestion @nelsontodd, makes perfect sense! Do you want to open a PR?

**Comment by nelsontodd** [comment]
Yes! Cool

**Comment by cedricleroy** [comment]
Closed with #23
