### ISSUE TITLE
Issue with single output being an array

### ISSUE THREAD

**Issue by anomam** [cedricleroy/pyungo#4]
Reference: https://github.com/cedricleroy/pyungo/blob/master/pyungo/core.py#L146-L152

I ran into an issue for a specific type of node. The node returns 1 output that is a list of multiple datetime objects (like a timestamps vector). Because of the lines referenced above, the graph only saves the 1st item of that returned list, because it thinks that multiple outputs will be returned (since ``iter(res)`` doesn't fail), but there is only one ``output_name`` in the node (like "timestamps" for instance).
Essentially, the ``for`` loop goes through the timestamps list, and returns the first element of that list as data to be saved...

**Comment by cedricleroy** [comment]
Fixed by #7
